/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
import { HTMLStencilElement, JSXBase } from "@stencil/core/internal";
import { Book } from "@nxworkspace/data-access/models";
export namespace Components {
    interface BookComponent {
        /**
          * The book to display
         */
        "book": Book;
    }
}
declare global {
    interface HTMLBookComponentElement extends Components.BookComponent, HTMLStencilElement {
    }
    var HTMLBookComponentElement: {
        prototype: HTMLBookComponentElement;
        new (): HTMLBookComponentElement;
    };
    interface HTMLElementTagNameMap {
        "book-component": HTMLBookComponentElement;
    }
}
declare namespace LocalJSX {
    interface BookComponent {
        /**
          * The book to display
         */
        "book"?: Book;
    }
    interface IntrinsicElements {
        "book-component": BookComponent;
    }
}
export { LocalJSX as JSX };
declare module "@stencil/core" {
    export namespace JSX {
        interface IntrinsicElements {
            "book-component": LocalJSX.BookComponent & JSXBase.HTMLAttributes<HTMLBookComponentElement>;
        }
    }
}
